events {
    worker_connections 1024;
}

http {
    upstream stock_market_servers {
        server instance1:8081;
        server instance2:8082;
        server instance3:8083;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://stock_market_servers;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}